spring.datasource.url=jdbc:postgresql://localhost:5432/fiver_clone
spring.datasource.username=postgres
spring.datasource.password=2057
spring.datasource.driver-class-name=org.postgresql.Driver
#JWT
jwt.secret=thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
jwt.expiration=3600000